### ISSUE TITLE
[Very high priority] Add a privacy policy and an impressum

### ISSUE THREAD

**Issue by stuxcrystal** [Irrational-Encoding-Wizardry/guide.encode.moe#26]
As per german TMG and european GDPR , we are legally required to have these two pages on the guide: *Impressum* and *Privacy Policy*.

You can take the privacy policy from `yuuno.encode.moe`.

Otherwise I will be forced to take down the guide.

You have 1 week time from the second I post this issue to add both pages until I take the site down.

----

> ### Impressum
> *Required by § 5 TMG (germany)*
> 
> FichteFoll's real name
> FichteFoll's real address
> 
> **Kontakt**
> Telefon: A phone number beloning to FichteFoll.
> E-Mail: An E-Mail address, you guessed it, belonging to FichetFoll.

**Comment by FichteFoll** [comment]
I metioned this on Discord, but I'm not willing to add my personal information on this site publicly.

If anyone else would like to volunteer and provide the requested information then I kindly invite you to make a pull request with this information or message me in any way and I'll go ahead and add it myself. Otherwise we will stop using the `yuuno.encode.moe` domain and instead go by `https://irrational-encoding-wizardry.github.io/guide.encode.moe` (or similar), potentially with a redirect from the old domain.

**Comment by stuxcrystal** [comment]
I kindly want to remind you that the actual location of the server hosting it does not matter for German law. Neither does the domain.
 It only matters whether the owner of the site is operating from Germany (or their services are primarily targeted to germans). 

I will further remind you that kageru, Frechdachs and me are operating this organization and by extension irrational-encoding-wizardry.github.io. All of us are German last I checked. 

Please note that if you choose someone in non-german EU, the page will fall under the jurisdiction of his country. In this case I'll be content to just name him somewhere on the page.

It doesn't save him from the requirements listed by GDPR. 

However IANAL.

**Comment by stuxcrystal** [comment]
Take my address if you want.

Just make sure that all images are stored inside the repo.

**Comment by OrangeChannel** [comment]
Are there any other rules besides picture hosting? Will add both pages shortly.

**Comment by stuxcrystal** [comment]
Where possible, prefer using Blender Foundation Movies for your examples.

I, of course, understand that this is not possible everywhere, especially where you discuss artifacts and so on.

But, for example, where you have previews of different editors, you can easily just load some Sintel or Big Buck Bunny images into it.

And for those where do you actually do use anime-examples, make sure users can see the what you're trying to explain easily.
