### ISSUE TITLE
Fix CD pipeline (and move to Github Actions)

### ISSUE THREAD

**Issue by FichteFoll** [Irrational-Encoding-Wizardry/guide.encode.moe#60]
Seems like our gitbook config broke out of nothing on Travis. Will need to investigate if that is the case generally or host-related.

I'll probably switch to using github actions and maybe also yarn in the process.

https://travis-ci.org/github/Irrational-Encoding-Wizardry/guide.encode.moe/builds/707148536

**Comment by OrangeChannel** [comment]
What do you think about migrating the book to rust's mdBook <https://github.com/rust-lang/mdBook>? The way to contribute to the book would stay the same and this seems pretty flexible, enough to support most of the stuff we have on the book now, while simplifying a lot and adding a few things that would be nice (like draft pages and allowing deeper section numbers for pages). It's also an actively maintained project and they seem pretty open to feature requests, and there's a recently opened PR + issue for "edit this page" functionality which is one of the things from old gitbook that's missing.

Not sure how migrating should happen though, ideally it would be nice to keep the current contributors list via the current commits but at the same time, the repo is becoming pretty large with all the image commits and changes.

**Comment by OrangeChannel** [comment]
https://github.com/OrangeChannel/guide.encode.moe/tree/mdbook I started testing with mdbook and it looks pretty good so far, a lot of pages have to change still though because of missing/changed features.

Preview at https://github.com/OrangeChannel/guide.encode.moe/tree/gh-pages but actual github pages won't build yet because of missing plug-ins etc.

**Comment by FichteFoll** [comment]
>the repo is becoming pretty large with all the image commits and changes.

We might want to consider moving the images to git LFS, especially since need to be lossless. The only problem is that it requires rewriting the history to properly prune them. But that's separate from the mdbook changes, which we'll discuss in #61.

**Comment by anonyno** [comment]
issue is because gitbook unmaintained https://github.com/Irrational-Encoding-Wizardry/guide.encode.moe/pull/62#issuecomment-699111841

**Comment by FichteFoll** [comment]
Indeed. #61 is there to address this, but I haven't been able to get around to that. Sorry about that, but it's on my radar.
